name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # 每天更新一次
  workflow_dispatch:     # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_achievements: yes
          # 取消过滤，先显示所有成就
          # plugin_achievements_only: sponsor, maintainer, octonaut
          plugin_languages: yes
          plugin_languages_details: bytes, percentage
          plugin_streak: yes
          plugin_commits: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_isocalendar: yes
          plugin_lines: yes
          config_timezone: Asia/Shanghai
