name: Metrics

on:
  schedule:
    # 每天 UTC 0 点更新一次
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_achievements: yes
          plugin_achievements_only: sponsor, maintainer, octonaut
          plugin_languages: yes
          plugin_languages_details: bytes, percentage
          plugin_streak: yes
          plugin_commits: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_isocalendar: yes
          plugin_lines: yes
          config_timezone: Asia/Shanghai
